node {
  stage('do something with git') {  
    sshagent (credentials: ['qsc-key']) {
      // get the last commit id from a repository you own
      sh 'git ls-remote -h --refs git@github.com:faraz891/jenkins-course.git master |awk "{print $1}"'
    }
  }
}
